const fs = require('fs');
const path = 'apps/api/src/lib/docx-generator.ts';
let code = fs.readFileSync(path, 'utf8');

const searchCode = "const docOptions: any = {\n    paragraphLoop: true,\n    linebreaks: true,\n    nullGetter: () => '',\n  };";
const replaceCode = "const docOptions: any = {\n    paragraphLoop: true,\n    linebreaks: true,\n    nullGetter: () => '',\n  };\n\n  // Auto-calculate budget totals if budget_items exists\n  if (Array.isArray(formData.budget_items)) {\n    const isMat = (b) => (b.category_name && b.category_name.includes('?????')) || Number(b.category_id) === 3 || (!b.category_name && !b.category_id && !(b.description || '').includes('??????') && !(b.description || '').includes('??????'));\n    const isSvc = (b) => (b.category_name && b.category_name.includes('??????')) || Number(b.category_id) === 2 || (!b.category_name && (b.description && (b.description.includes('??????') || b.description.includes('?????') || b.description.includes('??????') || b.description.includes('???????') || b.description.includes('????'))));\n    const isRem = (b) => (b.category_name && b.category_name.includes('??????')) || Number(b.category_id) === 1 || (!b.category_name && (b.description && (b.description.includes('??????') || b.description.includes('???????') || b.description.includes('???????'))));\n\n    let matBudget = 0;\n    let svcBudget = 0;\n    let remBudget = 0;\n\n    formData.budget_items.forEach(b => {\n      const amt = (Number(b.quantity) || 0) * (Number(b.unit_price) || 0);\n      if (isMat(b)) matBudget += amt;\n      else if (isSvc(b)) svcBudget += amt;\n      else if (isRem(b)) remBudget += amt;\n    });\n\n    formData.mat_total = matBudget > 0 ? matBudget.toLocaleString('th-TH', { minimumFractionDigits: 2 }) : '-';\n    formData.svc_total = svcBudget > 0 ? svcBudget.toLocaleString('th-TH', { minimumFractionDigits: 2 }) : '-';\n    formData.rem_total = remBudget > 0 ? remBudget.toLocaleString('th-TH', { minimumFractionDigits: 2 }) : '-';\n    const total = matBudget + svcBudget + remBudget;\n    formData.budget_total = total > 0 ? total.toLocaleString('th-TH', { minimumFractionDigits: 2 }) : '-';\n  }";

code = code.replace(searchCode, replaceCode);
fs.writeFileSync(path, code);
console.log('docx-generator patched for budgets');
