const fs = require('fs');
const path = 'apps/api/src/lib/docx-generator.ts';
let code = fs.readFileSync(path, 'utf8');

const searchCode = "    formData.mat_total = matBudget > 0 ? matBudget.toLocaleString('th-TH', { minimumFractionDigits: 2 }) : '-';\n    formData.svc_total = svcBudget > 0 ? svcBudget.toLocaleString('th-TH', { minimumFractionDigits: 2 }) : '-';\n    formData.rem_total = remBudget > 0 ? remBudget.toLocaleString('th-TH', { minimumFractionDigits: 2 }) : '-';\n    const total = matBudget + svcBudget + remBudget;\n    formData.budget_total = total > 0 ? total.toLocaleString('th-TH', { minimumFractionDigits: 2 }) : '-';\n  }";

const replaceCode = "    const matText = matBudget > 0 ? matBudget.toLocaleString('th-TH', { minimumFractionDigits: 2 }) : '-';\n    const svcText = svcBudget > 0 ? svcBudget.toLocaleString('th-TH', { minimumFractionDigits: 2 }) : '-';\n    const remText = remBudget > 0 ? remBudget.toLocaleString('th-TH', { minimumFractionDigits: 2 }) : '-';\n    const total = matBudget + svcBudget + remBudget;\n    const totalText = total > 0 ? total.toLocaleString('th-TH', { minimumFractionDigits: 2 }) : '-';\n\n    // Standard totals (put anywhere)\n    formData.mat_total = matText;\n    formData.svc_total = svcText;\n    formData.rem_total = remText;\n    formData.budget_total = totalText;\n\n    // Dynamic placement based on 'budget_type' field from frontend\n    const bt = (formData.budget_type || '').toString().trim();\n    const isGov = bt.includes('????????') && !bt.includes('??????');\n    const isIncome = bt.includes('??????');\n    const isSub = bt.includes('???????');\n    // Default to '???????' if it doesn't match above, but if it's completely empty, maybe default to income or just output dashes for all if we want to be strict. Let's just output dashes for all if it doesn't match, or if empty.\n    \n    const types = ['gov', 'income', 'sub', 'other'];\n    types.forEach(t => {\n      formData[mat_\] = '-';\n      formData[svc_\] = '-';\n      formData[em_\] = '-';\n      formData[	otal_\] = '-';\n    });\n\n    let target = 'other';\n    if (isGov) target = 'gov';\n    else if (isIncome) target = 'income';\n    else if (isSub) target = 'sub';\n\n    if (bt) { // Only map to specific column if budget_type is set\n      formData[mat_\] = matText;\n      formData[svc_\] = svcText;\n      formData[em_\] = remText;\n      formData[	otal_\] = totalText;\n    }\n  }";

code = code.replace(searchCode, replaceCode);
fs.writeFileSync(path, code);
console.log('patched advanced budget logic');
